//= require 'transition'
//= require 'dropdown'
//= require 'dimmer'
//= require 'modal'
//= require 'instafeed'
//= require 'jquery.bkgslide-1.0.4'
//= require 'ui'
//= require 'resy'
//= require_self
